In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd

import utils as u
import statsmodels.api as sm

In [3]:
#Read the dataset:
df = pd.read_csv("NSE-TATA.csv")
df.head()

#Analyze the closing prices from dataframe:+
df["Date"] = pd.to_datetime(df.Date,format="%Y-%m-%d")
df.index = df['Date']

#Sort the dataset on date time and # filter “Date” and “Close” columns:
data = df.sort_index(ascending=True,axis=0)
new_dataset = pd.DataFrame(index=range(0,len(df)),columns=['Date','Close'])
for i in range(0,len(data)):
    new_dataset["Date"][i] = data['Date'][i]
    new_dataset["Close"][i] = data["Close"][i]
# Normalize the new filtered dataset:
new_dataset.index = new_dataset.Date
new_dataset.drop("Date",axis=1,inplace=True)
dataset = new_dataset.values

# n previous close price wanna traning
number_of_previous_close_prices = 60

train_data,test_data = u.create_data(dataset,0.8)



x_train, y_train = u.create_x_y_train(train_data,number_of_previous_close_prices)
x_test, y_test = u.create_x_y_test(test_data,number_of_previous_close_prices)

247


In [4]:
x_train = sm.add_constant(x_train)

In [12]:
x_train.reshape(-1,1)
print(x_train)

[[1.0 155.8 155.55 ... 160.45 160.5 154.95]
 [1.0 155.55 160.15 ... 160.5 154.95 156.35]
 [1.0 160.15 160.05 ... 154.95 156.35 156.8]
 ...
 [1.0 166.55 169.5 ... 205.8 206.45 204.95]
 [1.0 169.5 173.75 ... 206.45 204.95 209.45]
 [1.0 173.75 175.4 ... 204.95 209.45 209.6]]


In [13]:
print(y_train)

[156.35 156.8  156.5  157.1  157.25 155.95 152.9  152.05 152.05 149.05
 146.2  148.3  147.85 149.85 148.2  144.25 141.35 138.95 142.15 140.45
 141.   140.7  143.15 143.05 141.15 143.35 143.6  144.85 144.05 141.75
 140.55 138.9  140.2  140.35 141.1  142.   142.7  141.2  139.8  139.7
 135.95 140.4  140.9  142.55 143.3  143.8  145.15 145.65 142.55 142.7
 143.15 141.3  141.4  143.4  143.65 142.85 142.9  142.75 141.8  148.
 150.05 154.25 153.5  151.55 152.2  151.45 154.4  153.1  152.75 153.05
 150.5  157.45 156.15 157.85 156.1  152.95 152.85 151.3  149.45 148.35
 146.7  145.1  144.6  142.45 145.   144.55 146.4  147.3  144.2  144.75
 150.7  153.45 153.1  155.55 157.55 156.45 156.4  156.25 148.9  149.1
 147.5  150.3  153.   154.05 171.1  171.2  174.85 169.35 168.65 163.7
 166.   167.05 163.55 162.9  162.35 167.95 167.3  169.5  167.8  171.1
 172.75 174.8  174.35 169.2  167.85 167.05 158.7  154.95 155.45 149.8
 151.8  153.75 157.2  160.35 160.65 159.2  158.7  156.8  156.55 153.5
 155.2  152.9  

In [10]:
print(x_train.shape, y_train.shape)

(928, 61) (928,)


In [16]:
y_train = np.array(y_train, dtype=float)
x_train = np.array(x_train, dtype=float)
model = sm.OLS(y_train, x_train)
results = model.fit()

In [17]:
results = model.fit() 

In [20]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.980
Model:                            OLS   Adj. R-squared:                  0.979
Method:                 Least Squares   F-statistic:                     705.5
Date:                Thu, 08 Jul 2021   Prob (F-statistic):               0.00
Time:                        22:40:45   Log-Likelihood:                -2234.1
No. Observations:                 928   AIC:                             4590.
Df Residuals:                     867   BIC:                             4885.
Df Model:                          60                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5574      0.977      0.571      0.5

In [21]:
print('coefficient of determination:', results.rsquared)
print('adjusted coefficient of determination:', results.rsquared_adj)
print('regression coefficients:', results.params)

coefficient of determination: 0.9799280228917286
adjusted coefficient of determination: 0.9785389587319867
regression coefficients: [ 5.57447681e-01  2.33962167e-02 -2.01194696e-03 -6.68591609e-03
 -1.91704275e-02 -3.25548995e-02  3.31469370e-02  6.79702242e-03
 -4.12076181e-02 -2.31542113e-02  4.58618560e-02 -3.32533716e-02
  4.83330747e-02 -1.06415869e-02 -7.05725084e-02  8.93943065e-02
 -4.75362183e-03 -2.07689740e-02  1.85754779e-02  2.63915450e-02
 -5.16857118e-02  3.98647215e-02  4.71936131e-03  2.35118084e-02
  9.28277100e-03 -1.71953862e-02 -8.14507864e-02  4.71665440e-02
 -1.90161681e-02  3.08375184e-02 -5.40786063e-02 -6.79906765e-03
  7.34498603e-02 -9.31133833e-04 -3.65806992e-02 -6.12853617e-03
  1.82870255e-02  1.00636655e-02 -4.00335604e-03  1.82069270e-02
 -9.92971926e-03 -2.28684532e-02 -1.82745102e-03 -1.14513372e-02
  8.72940526e-02 -1.06604528e-01  3.99608607e-02  1.06740116e-02
  6.69517901e-02 -1.51104680e-01  7.44679242e-02  1.66750309e-02
  3.58830373e-02 -1.002

In [25]:
x_test = sm.add_constant(x_test)
y_pred = results.predict(x_test)
y_pred

array([311.1507126289224, 312.19713658536006, 311.43157534231443,
       317.29862001678606, 315.63117874957896, 311.38186194989447,
       312.7754210964313, 328.3441202822211, 321.58750570171384,
       314.24693472339186, 312.06219381488756, 305.74275180602814,
       308.22350016825646, 311.4585248610257, 307.6521216887436,
       304.15092600301557, 305.95589849784136, 303.1527810835886,
       302.96311147075886, 291.2842257095261, 289.33465838082685,
       274.55783189167227, 275.1795961411726, 266.3803564898939,
       280.07660508769555, 279.54778276437594, 279.77534950037096,
       281.65761811242714, 283.33308372837166, 277.7945660944691,
       275.74833347295834, 266.4780851708511, 263.5653679049962,
       265.0755378611264, 264.7919176310492, 270.2192186722019,
       274.43324329815863, 275.2943003774327, 275.39108187571884,
       274.2009298608085, 275.37227349691585, 275.0398803533351,
       268.60937649461727, 273.4074951252221, 267.4651719325452,
       278.2036

In [26]:
for (e,r) in zip(y_test[:10],y_pred[:10]):
    print(e , r)


[312.25] 311.1507126289224
[312.95] 312.19713658536006
[317.6] 311.43157534231443
[315.3] 317.29862001678606
[314.1] 315.63117874957896
[313.3] 311.38186194989447
[325.75] 312.7754210964313
[323.0] 328.3441202822211
[316.4] 321.58750570171384
[313.55] 314.24693472339186


In [27]:
rmse = np.sqrt(np.mean(y_pred - y_test)**2)
print('rmse: ', rmse)

rmse:  0.22917667553765095


In [28]:
results.save('Linear_statsmodels.txt')

In [29]:
from statsmodels.regression.linear_model import OLSResults
new_results = OLSResults.load("Linear_statsmodels.txt")
print(new_results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.980
Model:                            OLS   Adj. R-squared:                  0.979
Method:                 Least Squares   F-statistic:                     705.5
Date:                Thu, 08 Jul 2021   Prob (F-statistic):               0.00
Time:                        22:51:25   Log-Likelihood:                -2234.1
No. Observations:                 928   AIC:                             4590.
Df Residuals:                     867   BIC:                             4885.
Df Model:                          60                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5574      0.977      0.571      0.5

In [30]:
print('coefficient of determination:', new_results.rsquared)
print('adjusted coefficient of determination:', new_results.rsquared_adj)
print('regression coefficients:', new_results.params)

coefficient of determination: 0.9799280228917286
adjusted coefficient of determination: 0.9785389587319867
regression coefficients: [ 5.57447681e-01  2.33962167e-02 -2.01194696e-03 -6.68591609e-03
 -1.91704275e-02 -3.25548995e-02  3.31469370e-02  6.79702242e-03
 -4.12076181e-02 -2.31542113e-02  4.58618560e-02 -3.32533716e-02
  4.83330747e-02 -1.06415869e-02 -7.05725084e-02  8.93943065e-02
 -4.75362183e-03 -2.07689740e-02  1.85754779e-02  2.63915450e-02
 -5.16857118e-02  3.98647215e-02  4.71936131e-03  2.35118084e-02
  9.28277100e-03 -1.71953862e-02 -8.14507864e-02  4.71665440e-02
 -1.90161681e-02  3.08375184e-02 -5.40786063e-02 -6.79906765e-03
  7.34498603e-02 -9.31133833e-04 -3.65806992e-02 -6.12853617e-03
  1.82870255e-02  1.00636655e-02 -4.00335604e-03  1.82069270e-02
 -9.92971926e-03 -2.28684532e-02 -1.82745102e-03 -1.14513372e-02
  8.72940526e-02 -1.06604528e-01  3.99608607e-02  1.06740116e-02
  6.69517901e-02 -1.51104680e-01  7.44679242e-02  1.66750309e-02
  3.58830373e-02 -1.002